name: Node.js

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  node:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar arquivos do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Verificar Node e npm
        run: |
          node --version
          npm --version
